In [55]:
import numpy as np
import math

In [56]:

#definicion de la funcion de jacobi 
def jacobi(A, b, x0, eps=1e-10, n = 500):   #valores por defecto en la funcion de jacobi 500 iteraciones
	D = np.diag(np.diag(A))
	LU = A - D
	x = x0
	for i in range(n):
		D_inv = np.linalg.inv(D)
		xTemp = x
		x = np.dot(D_inv, np.dot(-(LU), x) + b)    #jacobi 
		print('paso:', i, '- x:', x)
		if np.linalg.norm(x - xTemp) < eps:    #norm nos da la norma de un vector
			return x   #si converge regresa el valor calculado
	return x    #si no llego a convergencia regresa x 

In [69]:
# valores de prueba
#matriz A
A = np.array([
	[5, 2, 1, 1],
	[2, 6, 2, 1],
	[1, 2, 7, 1],
	[1, 1, 2, 8]
])

#matriz b transpuesta
b = np.array([29, 31, 26, 19])
x0 = np.random.rand(4)
# --------------------------------------
import numpy as np
from scipy import sparse

n = 100   #valor de prueba
matrizA = np.random.uniform(size=(n, n))
#print(X)

#X[X < 0.7] = 0   #matriz dispersa
A = np.array(matrizA)
b = np.random.uniform(n)
x0 = np.random.rand(n)

b = np.array(n)
x0 = np.array(n)

# -------------------------------------
#siendo n el numero de pasos
x = jacobi(A, b, x0, n = 10)     #si no ingresamos los ultimos valores, usa los valores por defecto la funcion
# x = jacobi(A, b, x0, 10**(-14), 500)
print("--------------------")
print('x:', x)
print("--------------------")
#print('b calculado:', np.dot(A,x))
#print('b verdadero:', b)
#solucion de numpy
#print('solucion de numpy:', np.linalg.solve(A,b))

paso: 0 - x: [[167.08600215  93.23278154  51.00779238 ...  50.66229057  36.15956102
   37.82914571]
 [167.03530929 191.01782365  52.44327559 ...  28.28437226  28.91274741
   77.71667841]
 [136.62162215  60.243213   139.14881189 ...  29.49383474  84.26993186
    9.91433159]
 ...
 [183.5280629  127.96285841 140.83135508 ... 223.83074379 194.66800841
   25.95407654]
 [686.51386312 406.25218762 610.61742192 ...  28.95290651 758.59351859
  402.80626692]
 [101.16890839  87.88205405  87.84192031 ...  70.17777395  48.31969782
  106.45491706]]
paso: 1 - x: [[-16066.69835997 -17809.13832716 -22821.42103172 ... -18733.98269554
  -22473.08989384 -21103.9419115 ]
 [-18801.7466541  -20862.75146374 -25793.56872966 ... -21657.63518298
  -24626.87629805 -24534.82405914]
 [-11332.81907168 -12775.89629817 -15076.11220703 ... -13532.74217411
  -13503.37780573 -13669.45304732]
 ...
 [-17074.59714677 -21588.48970345 -23871.19522392 ... -22401.38608581
  -25867.58336515 -23363.72913086]
 [-51387.4651109  -58

In [64]:
import numpy as np

#n = eval(input("Number of equations ==> "))

# ---------------------------------------------
#generacion de matriz dispersa

import numpy as np
from scipy.sparse import csr_matrix, csc_matrix


# --------------------------------------
import numpy as np
from scipy import sparse

n = 10   #valor de prueba
matrizA = np.random.uniform(size=(n, n))
#print(X)

#X[X < 0.7] = 0   #matriz dispersa
A = np.array(matrizA)
b = np.random.uniform(n)
x0 = np.random.rand(n)

#b = np.array(n)
#x0 = np.array(n)

# -------------------------------------

shapeDim = n

# ---------------------------------------------
#b = np.zeros(n)
rng = np.random.default_rng(seed=42)
#xarr = rng.random((n, n))
#print('A',xarr)
#A = xarr
A = sparseMatrixA

b = np.random.rand(n)
x0 = np.random.rand(n)
#b[n-1] = 1.0
#print('b',b)
#x = np.zeros(n)
#print('x',x)

x = jacobi(A, b, x0, n = 10) 

print(" --------SOLUCION ITERATIVA-------------------")
print('x:', x)
print(" ---------------------------------------------")
print('b calculado:', np.dot(A,x))
print('b verdadero:', b)
#print(" ---------SOLUCION NUMPY-----------------------")
#solucion de numpy
print('solucion de numpy:', np.linalg.solve(A,b))

LinAlgError: Singular matrix

In [62]:
#determinar si el sistema Ax = b es convergente para cualquier vector inicial x0

A = np.array([[29, 2, 1], [2, 6, 1], [1, 1, 1/5]])
D = np.diag(np.diag(A))
LU = A - D
BJ = np.dot(np.linalg.inv(D), -LU)
print(BJ)


[[ 0.         -0.06896552 -0.03448276]
 [-0.33333333  0.         -0.16666667]
 [-5.         -5.          0.        ]]


In [11]:
np.linalg.eig(BJ)

(array([-1.06609208,  0.11313964,  0.95295244]),
 array([[ 0.04268374,  0.51704948, -0.02380468],
        [ 0.16733135, -0.50135107, -0.16414591],
        [ 0.9849763 , -0.69376288,  0.9861488 ]]))

In [80]:
b = np.array([1,2,3])

x0 = np.zeros(3)
x = jacobi(A, b, x0)  

print('x:', x)
print('b calculado:', np.dot(A,x))
print('b verdadero:', b)
print('solucion de numpy:', np.linalg.solve(A, b))

ValueError: shapes (2,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

In [70]:
#definicion de la funcion de Gauss Seidel 
def gaussSeidel(A, b, x0, eps=1e-10, n = 500):   #valores por defecto en la funcion de jacobi
	D = np.diag(np.diag(A)); U = np.triu(A, k = 1); L = np.tril(A, k = -1)
	LU = A - D
	x = x0
    #D = np.diag(np.diag(A))
       
	for i in range(n):
		#D_inv = np.linalg.inv(D)
		LD_inv = np.linalg.inv(L+D)
		xTemp = x
		#x = np.dot(D_inv, np.dot(-(LU), x) + b)    #jacobi   
		x = np.dot( LD_inv ,(b - np.dot(U, x) ) )  #gauss seidel        
		print('paso:', i, '- x:', x)
		if np.linalg.norm(x - xTemp) < eps:    #norm nos da la norma de un vector
			return x   #si converge regresa el valor calculado
        
	return x    #si no llego a convergencia regresa x 


In [25]:
A = np.array([[29, 2, 1], [2, 6, 1], [1, 1, 1/5]])
D = np.diag(np.diag(A))
LU = A - D
BJ = np.dot(np.linalg.inv(D), -LU)
print(BJ)

[[ 0.         -0.06896552 -0.03448276]
 [-0.33333333  0.         -0.16666667]
 [-5.         -5.          0.        ]]


In [81]:
#matriz A
A = np.array([
	[5, 2, 1, 1],
	[2, 6, 2, 1],
	[1, 2, 7, 1],
	[1, 1, 2, 8]
])

#matriz b transpuesta
b = np.array([29, 31, 26, 19])
x0 = np.random.rand(4)

# --------------------------------------
import numpy as np
from scipy import sparse

n = 10   #valor de prueba
matrizA = np.random.uniform(size=(n, n))
#print(X)

#X[X < 0.7] = 0   #matriz dispersa
A = np.array(matrizA)
b = np.random.uniform(n)
x0 = np.random.rand(n)

b = np.array(n)
x0 = np.array(n)

# -------------------------------------
#siendo n el numero de pasos
x = gaussSeidel(A, b, x0)     #si no ingresamos los ultimos valores, usa los valores por defecto la funcion
# x = jacobi(A, b, x0, 10**(-14), 500)

print('x:', x)
print('b calculado:', np.dot(A,x))
print('b verdadero:', b)
#solucion de numpy

#print('solucion de numpy:', np.linalg.solve(A,b))

paso: 0 - x: [[ 3.63469816e+01  1.39378213e+01  1.43798381e+01  1.61949213e+01
   2.05901245e+01  1.20030437e+01  2.61560723e+01  1.36798545e+01
   3.44858477e+01  2.59977053e+01]
 [-1.45280963e+01  2.83090601e+01 -2.50031077e+01 -5.61480915e-02
  -3.81355415e+01 -4.68948209e+00 -1.34863208e+01  7.19407096e+00
  -3.67913143e+01 -2.59274786e+01]
 [ 1.90793669e+01 -3.26574849e+00  2.58271240e+01  9.05091393e+00
   2.74086823e+01  5.73099690e+00  6.38452783e+00  6.80524402e+00
   3.04410174e+01  2.34371466e+01]
 [-3.88337840e+00 -1.01741068e+01  4.69831346e+00 -5.97051238e-01
   5.48081250e-01  3.46800691e+00  6.46277648e+00 -1.27238278e+01
  -1.75902427e+00 -6.79959412e+00]
 [ 1.25249150e+01 -8.88329687e+00  1.45337809e+01  3.73240983e+00
   2.92450850e+01  4.14878433e+00  3.77557004e+00 -1.34237337e+00
   1.82614449e+01  2.20489367e+01]
 [ 7.27452831e+01 -1.83123605e+02  1.57570562e+02  2.65429038e+01
   2.87884619e+02  1.27188633e+02  1.39469230e+02 -8.75219109e+01
   1.21507510e+02  1

   2.62357492e+282  3.57137687e+282]]
paso: 160 - x: [[ 1.38649359e+282 -4.00520489e+282  3.65728233e+282  5.37547122e+281
   6.05536811e+282  2.50092225e+282  2.26206351e+282 -1.95303845e+282
   2.40471500e+282  3.27345084e+282]
 [-3.21996487e+282  9.30160739e+282 -8.49359904e+282 -1.24838864e+282
  -1.40628653e+283 -5.80809161e+282 -5.25337087e+282  4.53569726e+282
  -5.58466181e+282 -7.60219649e+282]
 [ 8.20110877e+281 -2.36907845e+282  2.16328228e+282  3.17959091e+281
   3.58174988e+282  1.47929536e+282  1.33801043e+282 -1.15522212e+282
   1.42238878e+282  1.93624598e+282]
 [ 1.01386885e+282 -2.92879282e+282  2.67437561e+282  3.93079555e+281
   4.42796790e+282  1.82879112e+282  1.65412646e+282 -1.42815290e+282
   1.75843989e+282  2.39370010e+282]
 [ 2.15401104e+282 -6.22235515e+282  5.68183406e+282  8.35115605e+281
   9.40742159e+282  3.88535091e+282  3.51426779e+282 -3.03417657e+282
   3.73588646e+282  5.08552602e+282]
 [ 3.05460013e+283 -8.82391339e+283  8.05740117e+283  1.184276

paso: 268 - x: [[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]
paso: 269 - x: [[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]
paso: 270 - x: [[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan n

paso: 375 - x: [[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]
paso: 376 - x: [[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]
paso: 377 - x: [[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan n

paso: 492 - x: [[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]
paso: 493 - x: [[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]
paso: 494 - x: [[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan n

In [79]:

# Defining our function as seidel which takes 3 arguments
# as A matrix, Solution and B matrix
   
def seidel(a, x ,b):
    #Finding length of a(3)       
    n = len(a)                   
    # for loop for 3 times as to calculate x, y , z
    for j in range(0, n):        
        # temp variable d to store b[j]
        d = b[j]                  
          
        # to calculate respective xi, yi, zi
        for i in range(0, n):     
            if(j != i):
                d-=a[j][i] * x[i]
        # updating the value of our solution        
        x[j] = d / a[j][j]
    # returning our updated solution           
    return x    
   
# int(input())input as number of variable to be solved                
n = 3                              
a = []                            
b = []        
# initial solution depending on n(here n=3)                     
x = [0, 0, 0]                        
a = [[4, 1, 2],[3, 5, 1],[1, 1, 3]]
b = [4,7,3]

# -------------------------------------
n = 2
x = np.zeros(n)

#matrizA = np.random.uniform(size=(n, n))
#print(X)

#X[X < 0.7] = 0   #matriz dispersa
#A = np.array(matrizA)
#b = np.random.uniform(n)
#x = np.random.rand(n)



# -------------------------------------
#print(x)
  
#loop run for m times depending on m the error value
for i in range(0, 25):            
    x = seidel(A, x, b)
    #print each time the updated solution
    print(x)             

[ 71.69848102 -80.15143434]
[  949.12423932 -1259.60445978]
[ 13860.71432838 -18615.61874321]
[ 203858.73644048 -274014.71078816]
[ 2999738.10974095 -4032290.95740517]
[ 44141963.60846189 -59336482.65515848]
[ 6.49562475e+08 -8.73154685e+08]
[ 9.55851163e+09 -1.28487400e+10]
[ 1.40656440e+11 -1.89073164e+11]
[ 2.06980281e+12 -2.78226980e+12]
[ 3.04577854e+13 -4.09419565e+13]
[ 4.48195687e+14 -6.02473490e+14]
[ 6.59533748e+15 -8.86558284e+15]
[ 9.7052421e+16 -1.3045978e+17]
[ 1.42815625e+18 -1.91975582e+18]
[ 2.10157587e+19 -2.82497977e+19]
[ 3.09253358e+20 -4.15704468e+20]
[ 4.55075834e+21 -6.11721920e+21]
[ 6.69658096e+22 -9.00167633e+22]
[ 9.85422500e+23 -1.32462438e+24]
[ 1.45007954e+25 -1.94922554e+25]
[ 2.13383667e+26 -2.86834538e+26]
[ 3.14000634e+27 -4.22085850e+27]
[ 4.62061597e+28 -6.21112320e+28]
[ 6.79937861e+29 -9.13985896e+29]
