# Gradiente conjugado

In [74]:
using Printf
using LinearAlgebra

In [75]:
function CGM(A::Array{Float64,2},b::Array{Float64,1},
                x0::Array{Float64,1},
                maxit::Int64=10,tol::Float64=1.0e-8,
                verbose=true)
    sol = deepcopy(x0)
    r = b - A*sol
    p = deepcopy(r)
    if verbose
        println("norm(r)     alpha        beta")
    end
    for i=1:maxit
        res = norm(r)
        if verbose
            sres = @printf("%.2e", res)
            print("$sres")
        end
        if res < tol
            if verbose
                println("  succeded after ", i, " steps")
            end
            return (sol, res, i, false)
        end
        
        alpha = (transpose(r)*r)/(transpose(p)*A*p)
        if verbose
            salpha = @sprintf("%.4e", alpha)
            print("  $salpha")
        end
        sol = sol + alpha*p
        r1 = r - alpha*A*p
        beta = (transpose(r1)*r1)/(transpose(r)*r)
        if verbose
            sbeta = @sprintf("%.4e", beta)
            println("   $sbeta")
        end
        p = r1 + beta*p
        r = r1
    end
    return (sol, norm(r), maxit, true)
end           

CGM (generic function with 4 methods)

In [76]:
#datos de prueba
mat = [2.0 2.0; 2.0 5.0]
rhs = [6.0; 3.0]
sol = [0.0; 0.0]
res = CGM(mat, rhs, sol)
println(res)

norm(r)     alpha        beta
6.71e+00nothing  2.3810e-01   3.2653e-01
3.83e+00nothing  7.0000e-01   0.0000e+00
0.00e+00nothing  succeded after 3 steps
([4.0, -1.0], 0.0, 3, false)


In [33]:
sol

2-element Vector{Float64}:
 0.0
 0.0

In [77]:
using Random


# 20, 40, 50, 80, 100
n = 4     #dimension de la matriz
b = randperm!(MersenneTwister(1234), Vector{Int}(undef, n))

brow = randperm!(MersenneTwister(1234), Vector{Int}(undef, n))
bcol = randperm!(MersenneTwister(1234), Vector{Int}(undef, n))
data = randperm!(MersenneTwister(1234), Vector{Int}(undef, n))

4-element Vector{Int64}:
 2
 1
 4
 3

In [78]:
c = rand(b, (n, n))

4×4 Matrix{Int64}:
 3  2  4  1
 4  1  3  4
 4  2  2  2
 4  3  2  3

In [26]:
sparseA = sparse(brow, bcol, data, n, n)

4×4 SparseMatrixCSC{Int64, Int64} with 4 stored entries:
 1  ⋅  ⋅  ⋅
 ⋅  2  ⋅  ⋅
 ⋅  ⋅  3  ⋅
 ⋅  ⋅  ⋅  4

In [28]:
#definicion de matriz dispersa A
sparseA =Matrix(sparseA)

4×4 Matrix{Int64}:
 1  0  0  0
 0  2  0  0
 0  0  3  0
 0  0  0  4

In [72]:
sparseA = float(sparseA)

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 0.0  2.0  0.0  0.0
 0.0  0.0  3.0  0.0
 0.0  0.0  0.0  4.0

In [51]:
rhsb = randperm!(MersenneTwister(1234), Vector{Int}(undef, 10))

10-element Vector{Int64}:
  2
  1
  7
  9
  5
 10
  4
  8
  6
  3

In [62]:
rh = float(rhsb)

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [52]:
#sol = randperm!(MersenneTwister(1234), Vector{Int}(undef, 10))
sol = zeros(n) 

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [68]:
using SparseArrays

# 20, 40, 50, 80, 100
n= 20
A = sprand(n,n,2/5)
A=Matrix(A)

20×20 Matrix{Float64}:
 0.0          0.0       0.0       0.0       …  0.485182   0.16092   0.0
 0.0          0.0       0.0       0.752798     0.0        0.709184  0.380373
 0.0          0.223612  0.0       0.605669     0.297549   0.185511  0.886959
 0.886926     0.893291  0.0       0.0          0.165256   0.0       0.0
 0.0          0.164133  0.0       0.0          0.0        0.258971  0.0
 0.264842     0.0       0.0       0.0       …  0.303143   0.0       0.395665
 0.0410201    0.0       0.946461  0.0          0.0        0.0       0.860836
 0.000278664  0.0       0.0       0.0          0.77689    0.0       0.150618
 0.0798506    0.197825  0.828687  0.55859      0.337489   0.0       0.0
 0.209536     0.0       0.0       0.398748     0.509302   0.0       0.99887
 0.341529     0.0       0.582262  0.0       …  0.0        0.0       0.242317
 0.802716     0.0       0.0       0.0          0.0        0.84655   0.0
 0.0          0.0       0.392536  0.0          0.0486939  0.0       0.42045
 0.

In [69]:
#rhsb = zeros(n)
rhsb = randperm!(MersenneTwister(1234), Vector{Int}(undef, n))
rhsb = float(rhsb)

20-element Vector{Float64}:
 16.0
 18.0
 14.0
 12.0
  5.0
 10.0
 20.0
 17.0
 13.0
  3.0
  7.0
  9.0
  6.0
 11.0
  8.0
  2.0
 15.0
  1.0
 19.0
  4.0

In [70]:
#sol = randperm!(MersenneTwister(1234), Vector{Int}(undef, 10))
sol = zeros(n) 

20-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [79]:
@time res = CGM(A, rhsb, sol)
println(res)

LoadError: DimensionMismatch("second dimension of A, 20, does not match length of x, 2")